#! /bin/sh

[ "${TRACE}" = 'YES' ] && set -x && : "$0" "$@"

###   ###   ###   ###   ###   ###   ###   ###   ###   ###   ###   ###   ###
MULLE_BASHFUNCTIONS_LIBEXEC_DIR="`mulle-bashfunctions libexec-dir`" || exit 1
export MULLE_BASHFUNCTIONS_LIBEXEC_DIR
. "${MULLE_BASHFUNCTIONS_LIBEXEC_DIR}/mulle-boot.sh" || exit 1
. "${MULLE_BASHFUNCTIONS_LIBEXEC_DIR}/mulle-bashfunctions.sh" || exit 1
###   ###   ###   ###   ###   ###   ###   ###   ###   ###   ###   ###   ###

if [ ! -z "${ZSH_VERSION}" ]
then
   setopt sh_word_split
fi



fail()
{
   echo "Unexpected failure" >&2
   stacktrace >&2
   exit 1
}

r_os_basename()
{
   # mingw basename is kinda broken, so we adapt here

   RVAL="`basename -- "$1" `"
   case "${MULLE_UNAME}" in   
      mingw)
         RVAL="${RVAL//\/\//\/}"
      ;;
   esac
}

test_basename()
{
   local filename="$1"

   local output

   r_basename "${filename}"
   output="${RVAL}"

   r_os_basename "${filename}"
   expected="${RVAL}"

   if [ "${output}" != "${expected}" ]
   then
      echo "\"${filename}\": got \"${output}\". Expected: \"${expected}\"" >&2
      stacktrace >&2
      exit 1
   fi
}



main()
{
   test_basename ""

   test_basename "."
   test_basename "/"
   test_basename "a"

#>>>
   test_basename "/."
   test_basename "//"
   test_basename "/a"

   test_basename "./"
   test_basename "a/"

   test_basename "./."
   test_basename ".//"
   test_basename "./a"

   test_basename "../"
   test_basename "/./"
   test_basename "a./"

   test_basename "/.."
   test_basename "/./"
   test_basename "/.a"

   test_basename "./."
   test_basename "//."
   test_basename "a/."

#>>>

   test_basename "./b"
   test_basename "//b"
   test_basename "a/b"

   test_basename "./b/"
   test_basename "//b/"
   test_basename "a/b/"

   test_basename "./b//"
   test_basename "//b//"
   test_basename "a/b//"

   echo "All tests passed" >&2
}


init()
{
   MULLE_BASHFUNCTIONS_LIBEXEC_DIR="${MULLE_BASHFUNCTIONS_LIBEXEC_DIR:-../../src}"

   . "${MULLE_BASHFUNCTIONS_LIBEXEC_DIR}/mulle-bashglobal.sh" || exit 1
   . "${MULLE_BASHFUNCTIONS_LIBEXEC_DIR}/mulle-compatibility.sh" || exit 1
   . "${MULLE_BASHFUNCTIONS_LIBEXEC_DIR}/mulle-string.sh" || exit 1
   . "${MULLE_BASHFUNCTIONS_LIBEXEC_DIR}/mulle-logging.sh" || exit 1
   . "${MULLE_BASHFUNCTIONS_LIBEXEC_DIR}/mulle-exekutor.sh" || exit 1
}


init "$@"
main "$@"

