#! /usr/bin/env bash

[ "${TRACE}" = 'YES' ] && set -x

if [ ! -z "${ZSH_VERSION}" ]
then
   setopt sh_word_split
fi



fail()
{
   echo "Unexpected failure" >&2
   stacktrace >&2
   exit 1
}


test_basename()
{
   local filename="$1"

   r_basename "${filename}"

   local output="${RVAL}"
   local expected="`basename -- "${filename}"`"

   if [ "${output}" != "${expected}" ]
   then
      echo "\"${filename}\": got \"${output}\". Expected: \"${expected}\"" >&2
      stacktrace >&2
      exit 1
   fi
}



main()
{
   test_basename ""

   test_basename "."
   test_basename "/"
   test_basename "a"

#>>>
   test_basename "/."
   test_basename "//"
   test_basename "/a"

   test_basename "./"
   test_basename "a/"

   test_basename "./."
   test_basename ".//"
   test_basename "./a"

   test_basename "../"
   test_basename "/./"
   test_basename "a./"

   test_basename "/.."
   test_basename "/./"
   test_basename "/.a"

   test_basename "./."
   test_basename "//."
   test_basename "a/."

#>>>

   test_basename "./b"
   test_basename "//b"
   test_basename "a/b"

   test_basename "./b/"
   test_basename "//b/"
   test_basename "a/b/"

   test_basename "./b//"
   test_basename "//b//"
   test_basename "a/b//"

   echo "All tests passed" >&2
}


init()
{
   MULLE_BASHFUNCTIONS_LIBEXEC_DIR="${MULLE_BASHFUNCTIONS_LIBEXEC_DIR:-../../src}"

   . "${MULLE_BASHFUNCTIONS_LIBEXEC_DIR}/mulle-compatibility.sh" || exit 1
   . "${MULLE_BASHFUNCTIONS_LIBEXEC_DIR}/mulle-string.sh" || exit 1
   . "${MULLE_BASHFUNCTIONS_LIBEXEC_DIR}/mulle-logging.sh" || exit 1
}


init "$@"
main "$@"

