#! /usr/bin/env bash

[ "${TRACE}" = 'YES' ] && set -x

if [ ! -z "${ZSH_VERSION}" ]
then
   setopt sh_word_split
fi


fail()
{
   echo "Unexpected failure" >&2
   stacktrace >&2
   exit 1
}


r_os_dirname()
{
   # mingw basename is kinda broken, so we adapt here

   RVAL="`dirname -- "$1" `"
   case "${MULLE_UNAME}" in   
      mingw)
         RVAL="${RVAL//\/\//\/}"
      ;;
   esac
}

test_dirname()
{
   local filename="$1"

   local output

   r_dirname "${filename}"
   output="${RVAL}"

   r_os_dirname "${filename}"
   expected="${RVAL}"

   if [ "${output}" != "${expected}" ]
   then
      echo "\"${filename}\": got \"${output}\". Expected: \"${expected}\"" >&2
      stacktrace >&2
      exit 1
   fi
}



main()
{
   test_dirname ""

   test_dirname "."
   test_dirname "/"
   test_dirname "a"

#>>>
   test_dirname "/."
   test_dirname "//"
   test_dirname "/a"

   test_dirname "./"
   test_dirname "a/"

   test_dirname "./."
   test_dirname ".//"
   test_dirname "./a"

   test_dirname "../"
   test_dirname "/./"
   test_dirname "a./"

   test_dirname "/.."
   test_dirname "/./"
   test_dirname "/.a"

   test_dirname "./."
   test_dirname "//."
   test_dirname "a/."

#>>>

   test_dirname "./b"
   test_dirname "//b"
   test_dirname "a/b"

   test_dirname "./b/"
   test_dirname "//b/"
   test_dirname "a/b/"

   test_dirname "./b//"
   test_dirname "//b//"
   test_dirname "a/b//"

   test_dirname "/./b//"
   test_dirname "///b//"
   test_dirname "/a/b//"

   case "${MULLE_UNAME}" in 
      mingw)
         # interestingly mingw does it better sort of 
         # but its no use to us
      ;;

      *)
         test_dirname "//./b//"
         test_dirname "//a/b//"
      ;;
   esac
   test_dirname "////b//"

   echo "All tests passed" >&2
}


init()
{
   MULLE_BASHFUNCTIONS_LIBEXEC_DIR="${MULLE_BASHFUNCTIONS_LIBEXEC_DIR:-../../src}"

   . "${MULLE_BASHFUNCTIONS_LIBEXEC_DIR}/mulle-bashglobal.sh" || exit 1
   . "${MULLE_BASHFUNCTIONS_LIBEXEC_DIR}/mulle-compatibility.sh" || exit 1
   . "${MULLE_BASHFUNCTIONS_LIBEXEC_DIR}/mulle-string.sh" || exit 1
   . "${MULLE_BASHFUNCTIONS_LIBEXEC_DIR}/mulle-logging.sh" || exit 1
}


init "$@"
main "$@"

