#! /usr/bin/env bash

[ "${TRACE}" = 'YES' ] && set -x

TEST_DIR="`dirname -- "$0"`"
PROJECT_DIR="$( cd "${TEST_DIR}/.." ; pwd -P)"

MULLE_BASHFUNCTIONS_LIBEXEC_DIR="${MULLE_BASHFUNCTIONS_LIBEXEC_DIR:-../../src}"
export MULLE_BASHFUNCTIONS_LIBEXEC_DIR

main()
{
   local i

   for i in "${TEST_DIR}"/*
   do
      if [ -x "$i/run-test" ]
      then
         printf "%s\n" "------------------------------------------" >&2
         printf "%s\n" "$i:" >&2
         printf "%s\n" "------------------------------------------" >&2
         ( cd "$i" && ./run-test "$@" ) || exit 1
      fi
   done
}

main "$@"
