#! /usr/bin/env bash

[ "${TRACE}" = 'YES' ] && set -x


stacktrace()
{
   local i=1
   local line

   while line="`caller $i`"
   do
      printf "${C_CYAN}%b${C_RESET}\n" "$i: #${line}"
      ((i++))
   done
}


fail()
{
   echo "Unexpected failure" >&2
   stacktrace >&2
   exit 1
}


test_basename()
{
   local filename="$1"


   local output="`fast_basename "${filename}"`"
   local expected="`basename -- "${filename}"`"

   if [ "${output}" != "${expected}" ]
   then
      echo "\"${filename}\": got \"${output}\". Expected: \"${expected}\"" >&2
      stacktrace >&2
      exit 1
   fi
}



main()
{
   test_basename ""

   test_basename "."
   test_basename "/"
   test_basename "a"

#>>>
   test_basename "/."
   test_basename "//"
   test_basename "/a"

   test_basename "./"
   test_basename "a/"

   test_basename "./."
   test_basename ".//"
   test_basename "./a"

   test_basename "../"
   test_basename "/./"
   test_basename "a./"

   test_basename "/.."
   test_basename "/./"
   test_basename "/.a"

   test_basename "./."
   test_basename "//."
   test_basename "a/."

#>>>

   test_basename "./b"
   test_basename "//b"
   test_basename "a/b"

   test_basename "./b/"
   test_basename "//b/"
   test_basename "a/b/"

   test_basename "./b//"
   test_basename "//b//"
   test_basename "a/b//"

   echo "All tests passed" >&2
}


init()
{
   MULLE_BASHFUNCTIONS_LIBEXEC_DIR="${MULLE_BASHFUNCTIONS_LIBEXEC_DIR:-../../src}"

   . "${MULLE_BASHFUNCTIONS_LIBEXEC_DIR}/mulle-string.sh" || exit 1
}


init "$@"
main "$@"

