#! /bin/sh

[ "${TRACE}" = 'YES' ] && set -x && : "$0" "$@"

###   ###   ###   ###   ###   ###   ###   ###   ###   ###   ###   ###   ###
MULLE_BASHFUNCTIONS_LIBEXEC_DIR="${MULLE_BASHFUNCTIONS_LIBEXEC_DIR:-`mulle-bashfunctions libexec-dir`}" || exit 1

. "${MULLE_BASHFUNCTIONS_LIBEXEC_DIR}/mulle-boot.sh"          || exit 1
. "${MULLE_BASHFUNCTIONS_LIBEXEC_DIR}/mulle-bashglobal.sh"    || exit 1
. "${MULLE_BASHFUNCTIONS_LIBEXEC_DIR}/mulle-compatibility.sh" || exit 1
. "${MULLE_BASHFUNCTIONS_LIBEXEC_DIR}/mulle-logging.sh"       || exit 1
. "${MULLE_BASHFUNCTIONS_LIBEXEC_DIR}/mulle-options.sh"       || exit 1
. "${MULLE_BASHFUNCTIONS_LIBEXEC_DIR}/mulle-string.sh"        || exit 1
. "${MULLE_BASHFUNCTIONS_LIBEXEC_DIR}/mulle-path.sh"          || exit 1
. "${MULLE_BASHFUNCTIONS_LIBEXEC_DIR}/mulle-exekutor.sh"      || exit 1
. "${MULLE_BASHFUNCTIONS_LIBEXEC_DIR}/mulle-file.sh"          || exit 1
###   ###   ###   ###   ###   ###   ###   ###   ###   ###   ###   ###   ###

if [ ${ZSH_VERSION+x} ]
then
   setopt sh_word_split
fi


expect_output()
{
   local output="$1"
   local expected="$2"

   if [ "${output}" != "${expected}" ]
   then
      echo "Got \"${output}\". Expected: \"${expected}\"" >&2
      stacktrace >&2
      exit 1
   fi
}


test_trim_whitespace()
{
   r_trim_whitespace ""
   expect_output "${RVAL}" ""

   r_trim_whitespace "  hello  "
   expect_output "${RVAL}" "hello"

   r_trim_whitespace "	hello	"
   expect_output "${RVAL}" "hello"

   r_trim_whitespace "  hello world  "
   expect_output "${RVAL}" "hello world"
}


test_upper_firstchar()
{
   r_upper_firstchar ""
   expect_output "${RVAL}" ""

   r_upper_firstchar "hello"
   expect_output "${RVAL}" "Hello"

   r_upper_firstchar "Hello"
   expect_output "${RVAL}" "Hello"
}


test_extended_identifier()
{
   r_extended_identifier ""
   expect_output "${RVAL}" ""

   r_extended_identifier "hello world"
   expect_output "${RVAL}" "hello_world"

   r_extended_identifier "hello_world"
   expect_output "${RVAL}" "hello_world"

   r_extended_identifier "hello-world"
   expect_output "${RVAL}" "hello-world"

   r_extended_identifier "hello@world"
   expect_output "${RVAL}" "hello_world"
}


main()
{
   test_trim_whitespace
   test_upper_firstchar
   test_extended_identifier

   echo "All tests passed" >&2
}


main "$@"
