#! /bin/sh

[ "${TRACE}" = 'YES' ] && set -x && : "$0" "$@"

###   ###   ###   ###   ###   ###   ###   ###   ###   ###   ###   ###   ###
MULLE_BASHFUNCTIONS_LIBEXEC_DIR="`mulle-bashfunctions libexec-dir`" || exit 1
export MULLE_BASHFUNCTIONS_LIBEXEC_DIR
. "${MULLE_BASHFUNCTIONS_LIBEXEC_DIR}/mulle-boot.sh" || exit 1
. "${MULLE_BASHFUNCTIONS_LIBEXEC_DIR}/mulle-bashfunctions.sh" || exit 1
###   ###   ###   ###   ###   ###   ###   ###   ###   ###   ###   ###   ###

if [ ! -z "${ZSH_VERSION}" ]
then
   setopt sh_word_split
fi

run_test()
{
  expect="$1"
  shift

  result="`eval "$@"`"

  [ "${result}" != "${expect}" ] && fail "test:" "$@" "failed with \"${result}\", expected \"${expect}\""
  :
}


compute_relative()
{
   r_compute_relative "$@"

   [ ! -z "${RVAL}" ] && printf "%s\n" "${RVAL}"
}



test_compute_relative()
{
  run_test ""            compute_relative ""

  run_test ""            compute_relative "/"
  run_test ".."          compute_relative "/."
  run_test ".."          compute_relative "/./"
  run_test "../.."       compute_relative "/foo/.."
  run_test "../.."       compute_relative "/foo/../"
  run_test "../../.."    compute_relative "/foo/../../"

  run_test "../.."       compute_relative "/foo/bar"
  run_test "../../../.." compute_relative "foo/../../bar"

  run_test ".."          compute_relative "foo"
  run_test "../.."       compute_relative "foo/bar"
}


relative_path_between()
{
   r_relative_path_between "$@"

   [ ! -z "${RVAL}" ] && printf "%s\n" "${RVAL}"
}


test_relative_path_between()
{
  run_test "."      relative_path_between /a /a
  run_test "."      relative_path_between /a /a/
  run_test "."      relative_path_between /a/ /a
  run_test "."      relative_path_between /a/ /a
  run_test "b"      relative_path_between /a/b /a
  run_test "b/c"    relative_path_between /a/b/c /a
  run_test "../b"   relative_path_between /b /a
  run_test "../b/c" relative_path_between /b/c /a

  run_test ".."     relative_path_between /a /a/b
  run_test "."      relative_path_between /a/b /a/b
  run_test "c"      relative_path_between /a/b/c /a/b

  run_test "../../b/c" relative_path_between /b/c /a/b
  run_test "../../c"   relative_path_between /c /a/b

  run_test "../.."  relative_path_between /a /a/b/c

  run_test "."      relative_path_between a a
  run_test "b/c"    relative_path_between a/b/c a

  run_test ".."     relative_path_between a a/b
  run_test "c"      relative_path_between a/b/c a/b

  run_test "../.."  relative_path_between a a/b/c
  run_test ".."     relative_path_between a/b a/b/c
  run_test "../../a/b"     relative_path_between a/b c/d

  run_test "../../.repos/.embedded" relative_path_between .repos/c/.repos/.embedded .repos/c/src/b_1

}


main()
{
   _options_mini_main "$@" && set -x

   test_compute_relative
   test_relative_path_between

   log_info "----- ALL PASSED -----"
}


init()
{
   MULLE_BASHFUNCTIONS_LIBEXEC_DIR="${MULLE_BASHFUNCTIONS_LIBEXEC_DIR:-../../src}"

   . "${MULLE_BASHFUNCTIONS_LIBEXEC_DIR}/mulle-bashfunctions.sh" || exit 1
}


init "$@"
main "$@"

