#! /usr/bin/env bash

[ "${TRACE}" = 'YES' ] && set -x


stacktrace()
{
   local i=1
   local line

   while line="`caller $i`"
   do
      printf "${C_CYAN}%b${C_RESET}\n" "$i: #${line}"
      ((i++))
   done
}


expect_output()
{
   local output="$1"
   local expected="$2"

   if [ "${output}" != "${expected}" ]
   then
      echo "Got \"${output}\". Expected: \"${expected}\"" >&2
      stacktrace >&2
      exit 1
   fi
}


fail()
{
   echo "Unexpected failure" >&2
   stacktrace >&2
   exit 1
}


test_backslash()
{
   local output

# EMPTY STRING
   r_escaped_backslashes ''
   expect_output "${RVAL}" ""

   r_escaped_backslashes 'a'
   expect_output "${RVAL}" "a"

   r_escaped_backslashes '\'
   expect_output "${RVAL}" '\\'

   r_escaped_backslashes '\\'
   expect_output "${RVAL}" '\\\\'
}


test_doublequote()
{
   local output

# EMPTY STRING
   r_escaped_doublequotes ''
   expect_output "${RVAL}" ""

   r_escaped_doublequotes 'a'
   expect_output "${RVAL}" 'a'

   r_escaped_doublequotes '"'
   expect_output "${RVAL}" '\"'

   r_escaped_doublequotes '\"'
   expect_output "${RVAL}" '\\\"'

   r_escaped_doublequotes '""'
   expect_output "${RVAL}" '\"\"'

   r_escaped_doublequotes '"\\"'
   expect_output "${RVAL}" '\"\\\\\"'
}


test_comma_concat()
{
   local output

# EMPTY STRING
   output="`comma_concat "" ""`"
   expect_output "${output}" ""

   output="`comma_concat "," ""`"
   expect_output "${output}" ""

# ,
   output="`comma_concat "" ","`"
   expect_output "${output}" ""

   output="`comma_concat "," ","`"
   expect_output "${output}" ""

# ,,
   output="`comma_concat "" ",,"`"
   expect_output "${output}" ""

   output="`comma_concat ",," ",,"`"
   expect_output "${output}" ""

# a
   output="`comma_concat "a" ""`"
   expect_output "${output}" "a"

   output="`comma_concat "" "a"`"
   expect_output "${output}" "a"

# a,
   output="`comma_concat "a," ""`"
   expect_output "${output}" "a"

   output="`comma_concat "" "a,"`"
   expect_output "${output}" "a"

# ,a
   output="`comma_concat ",a" ""`"
   expect_output "${output}" "a"

   output="`comma_concat "" ",a"`"
   expect_output "${output}" "a"

# ,a,
   output="`comma_concat ",a," ""`"
   expect_output "${output}" "a"

   output="`comma_concat "" ",a,"`"
   expect_output "${output}" "a"

# a b
   output="`comma_concat "a" "b"`"
   expect_output "${output}" "a,b"

# ,a, ,b,
   output="`comma_concat ",a," ",b,"`"
   expect_output "${output}" "a,b"
}


main()
{
   test_backslash
   test_doublequote

   echo "All tests passed" >&2
}


init()
{
   MULLE_BASHFUNCTIONS_LIBEXEC_DIR="${MULLE_BASHFUNCTIONS_LIBEXEC_DIR:-../../src}"

   . "${MULLE_BASHFUNCTIONS_LIBEXEC_DIR}/mulle-string.sh" || exit 1
}


init "$@"
main "$@"

