name: CI

on: [push,workflow_dispatch]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest ]

    steps:
    - uses: actions/checkout@v3

    - name: Test
      run: |
        PATH="${PATH}:${PWD}"
        echo "$PATH" >&2
        ( cd test && ./run-test )

    - name: Test Installer
      run: |
        mkdir /tmp/xxx
        ./bin/installer /tmp/xxx
        PATH=/tmp/xxx/bin:$PATH
        echo "$PATH" >&2
        mulle-bashfunctions env